fn main() {
    println!("Chapter 9 Error Handling");
}
